match_dataset_name: !!str "cifar10"
corrupted_dataset_name: !!str "cifar10c"
model_seed: !!int 1
data_path: "data"
batch_size: !!int 1000
epochs: !!int 100
lr: !!float 0.1
lbds: !!seq
  - 1.
  - .8
  - .6
  - .5
  # - .4

rs: !!seq
  - 10
  - 5
  - 3
  - 2

seeds: !!seq
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10

temperatures: !!seq
  - 1.
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 2.
  - 2.5
  - 3.
  - 100.
  - 1000.

magnitudes:
  - 0.
  - .0002
  - .00025
  - .0003
  - .00035
  - .0004
  - .0006
  - .0008
  - .001
  - .0012
  - .0014
  - .0016
  - .0018
  - .002
  - .0022
  - .0024
  - .0026
  - .0028
  - .003
  - .0032
  - .0034
  - .0036
  - .0038
  - .004

intensities: !!seq
  # - 1
  # - 2
  # - 3
  # - 4
  - 5

corruptions: !!seq
  - "brightness"
  - "contrast"
  - "defocus_blur"
  - "elastic_transform"
  - "fog"
  - "frost"
  - "gaussian_blur"
  - "gaussian_noise"
  - "glass_blur"
  - "impulse_noise"
  - "jpeg_compression"
  - "motion_blur"
  - "pixelate"
  - "saturate"
  - "shot_noise"
  - "snow"
  - "spatter"
  - "speckle_noise"
  - "zoom_blur"
