model_name: !!str "resnet34_custom_regmixup"
match_dataset_name: !!str "cifar10"
mismatch_dataset_name: !!str "cifar100"
model_seed: !!int 1
data_path: "./data"
device_id: !!int 0
batch_size: !!int 1000
rs: !!seq
  - 10
  - 5
  - 3
  - 2

seeds: !!seq
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
temperatures: !!seq
  - 1.
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 2.
  - 2.5
  - 3.
  - 100.
  - 1000.
magnitudes:
  - 0.
  - .0002
  - .00025
  - .0003
  - .00035
  - .0004
  - .0006
  - .0008
  - .001
  - .0012
  - .0014
  - .0016
  - .0018
  - .002
  - .0022
  - .0024
  - .0026
  - .0028
  - .003
  - .0032
  - .0034
  - .0036
  - .0038
  - .004
